"""Weather enrichment node for route planning preferences and hiker guidance."""

from datetime import date

from pydantic import BaseModel, Field

from services.weather_service import weather_lookup_tool


class WeatherAssessment(BaseModel):
    """Structured weather-aware guidance generated by the LLM."""

    clothing_advice: list[str] = Field(description="Specific practical clothing and gear advice based on this forecast")
    route_guidance: str = Field(description="Brief explanation of how this forecast should influence the hike")
    avoid_unpaved: bool = Field(description="Whether the forecast makes unpaved paths undesirable")
    prefer_forest: bool = Field(description="Whether the forecast makes forest cover preferable")


def weather_node(state: dict) -> dict:
    """Use the parsed route position and date to enrich weather-sensitive intent."""
    route_request = state.get("route_request") or {}
    start_point = route_request.get("start_point")
    if not start_point:
        return {"weather_report": None, "weather_error": "Weather check skipped: no route position."}

    forecast_date = route_request.get("hike_date") or date.today().isoformat()
    try:
        report = weather_lookup_tool.invoke({
            "latitude": start_point[0],
            "longitude": start_point[1],
            "forecast_date": forecast_date,
        })
    except Exception as error:
        print(f"[Weather Agent] Forecast unavailable: {error}")
        return {"weather_report": None, "weather_error": str(error)}

    llm = state.get("_llm")
    assessment_prompt = f"""
    You are an experienced hiking guide. Reason about this structured weather forecast
    and produce practical advice for the hiker. Do not use fixed temperature thresholds
    or generic rules; consider all available conditions together, including temperature,
    rain, precipitation probability, showers, snowfall, and wind.

    Weather data:
    {report}

    Decide whether wet ground makes unpaved paths undesirable and whether forest cover
    would improve comfort. Explain the reasoning briefly in route_guidance. Clothing
    advice should be concise, specific, and useful for this exact forecast.
    """
    assessment = llm.with_structured_output(WeatherAssessment).invoke(assessment_prompt)
    preferences = dict(route_request.get("environmental_preferences") or {})
    if assessment.avoid_unpaved and preferences.get("avoid_mud"):
        preferences["avoid_unpaved"] = True
        preferences["prefer_paved"] = True
    if assessment.prefer_forest and not preferences.get("avoid_green") and not preferences.get("avoid_forest"):
        preferences["prefer_forest"] = True

    enriched_request = dict(route_request)
    enriched_request["environmental_preferences"] = preferences
    report["clothing_advice"] = assessment.clothing_advice
    report["route_guidance"] = assessment.route_guidance
    return {"route_request": enriched_request, "weather_report": report, "weather_error": None}